#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2021.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Fri Oct 14 19:29:05 EEST 2022
# SW Build 3367213 on Tue Oct 19 02:47:39 MDT 2021
#
# IP Build 3369179 on Thu Oct 21 08:25:16 MDT 2021
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim ALU_test_behav -key {Behavioral:sim_1:Functional:ALU_test} -tclbatch ALU_test.tcl -log simulate.log"
xsim ALU_test_behav -key {Behavioral:sim_1:Functional:ALU_test} -tclbatch ALU_test.tcl -log simulate.log

